logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.jcb.assessment: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://pgm-2zero0a42q465gi1io.pg.rds.aliyuncs.com:1433/jcb_download_service_test?createDatabaseIfNotExist=true&useSSL=true&characterEncoding=utf-8
    username: uugmpg
    password: Joke@123098
    hikari:
      database: postgresql
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 2
  jpa:
    show-sql: true
server:
  port: 8080

service-url:
  #  url: http://localhost:9000/
  #  url: http://39.103.13.40/
  huobi: http://api.testnet.huobi.pro/v1/
  download: http://test.pro.jianchaba.com:5008/api/v1/
